# Generated by Django 5.1 on 2024-08-24 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='endgame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('disasterTp', models.CharField(max_length=100)),
                ('disasterDt', models.CharField(max_length=1000)),
            ],
        ),
    ]
